name: CI Ubuntu Latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install libhdf5-dev 
        sudo apt-get install libhdf5-serial-dev
        sudo apt-get install libhdf5-100
        sudo apt-get install libqtgui4 
        sudo apt-get install libqtwebkit4
        sudo apt-get install libqt4-test
        sudo apt-get install python3-pyqt5
        sudo apt-get install libatlas-base-dev
        sudo apt-get install python-opencv
        pip install flake8
        pip install filterpy
        pip install imutils
        pip install matplotlib
        pip install numpy
        pip install Pillow
        pip install opencv-python
        pip install scipy
        pip install scikit-image
        pip install https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-linux_x86_64.whl
        pip install git+https://github.com/nathanrooy/rpi-urban-mobility-tracker
    - name: Test with unittest
      run: python -m unittest tests/unit/test_utils.py
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
